#
#-- Copyright (C) 2018 dz <dingzhong110@gmail.com>
# Copyright (C) 2021-2022  sirpdboy  <herboy2008@gmail.com> https://github.com/sirpdboy/luci-app-cupsd
# Copyright (C) 2026-  xmprocat  <y6518@live.com> https://github.com/xmprocat/PrinterMgr
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for printer manager
LUCI_DEPENDS:= +cups
PKG_VERSION:=1.0.1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
