#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@cupsd[-1]
	add ucitrack cupsd
	set ucitrack.@cupsd[-1].init=cupsd
	# also register samba4 (if present)
	delete ucitrack.@samba4[-1]
	add ucitrack samba4
	set ucitrack.@samba4[-1].init=samba4
	commit ucitrack
EOF


rm -f /tmp/luci*
exit 0
